services:
  # ----------------------------------------------------------------------------------------------------------------------------------------
  app:  
    image: app-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app 
      - /usr/src/app/node_modules
    container_name: front-dev
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - WDS_SOCKET_PORT=0      
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    ports:
      - "8080:3000"  # Expose the development server port
  # ----------------------------------------------------------------------------------------------------------------------------------------
  server:
    image: backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile    
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    container_name: back-dev
    ports:
      - "3001:3000"
