# fly.toml app configuration file generated for wild-fire-5805 on 2023-08-23T22:08:05+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wild-fire-5805"
primary_region = "ams"

[build]
  [build.args]
    NODE_VERSION = "20.5.1"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]